base_url: "https://thanos.nrp-nautilus.io/api/v1/query_range"
step: 3600
queries: 
    status: |
        kube_pod_status_phase{
            phase=~"Running|Pending", 
            namespace=~"csusb.*|csu.*|ccp-.*|cal-poly-.*|sdsu-.*|csun-.*|nsf-maica",
            namespace!~"sdsu-jupyterhub.*"
        }
    truth: |
        kube_pod_container_resource_requests{
            namespace=~"csusb.*|csu.*|ccp-.*|cal-poly-.*|sdsu-.*|csun-.*|nsf-maica",
            namespace!~"sdsu-jupyterhub.*", 
            resource = "%TYPE_STRING%", 
            node=~"rci-tide.*|rci-nrp-gpu-08.*|rci-nrp-gpu-07.*|rci-nrp-gpu-06.*|rci-nrp-gpu-05.*", 
            node!~"rci-tide-dtn.*"
        }
top5hours_blacklist:
  - sdsu-rci-jh
  - csu-tide-jupyterhub
  - csusb-jupyterhub