period: March25
ingest:
  PromQLIngestController:
    - monthly
    - tainted
  IngestTimeline:
analysisdriver:
  AvailableHoursDriver:
    # Information about hardware configurations for each node.
    default:
      rci-tide-cpu:
        cpu: 64
        gpu: 4
        node_cnt: 6
      rci-tide-gpu:  # Targets L40 GPUs
        cpu: 24
        gpu: 4
        node_cnt: 17
      rci-nrp-gpu:  # Targets A100 GPUs
        cpu: 64
        gpu: 4
        node_cnt: 8
  SummaryDriver:
    top5hours_blacklist:
      - sdsu-rci-jh
      - csu-tide-jupyterhub
      - csusb-jupyterhub